river-aflfast-0_1   |     self._process_test_case()
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/watcher.py", line 182, in _process_test_case
driver-aflfast-0_1   |     server_id = self._connection.push_test_case(seed_msg)
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 132, in push_test_case
driver-parmesan-0_1  |     self._process_test_case()
driver-parmesan-0_1  |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/watcher.py", line 182, in _process_test_case
driver-parmesan-0_1  |     server_id = self._connection.push_test_case(seed_msg)
driver-parmesan-0_1  |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 132, in push_test_case
driver-symcc-0_1     |     self._connection.report_ready()
driver-symcc-0_1     |     self._process_test_case()
driver-symcc-0_1     |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 178, in report_ready
driver-symcc-0_1     |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/watcher.py", line 182, in _process_test_case
driver-parmesan-0_1  |     self.__poll_socket(self._report_socket)
driver-parmesan-0_1  |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 240, in __poll_socket
driver-aflfast-0_1   |     self.__poll_socket(self._report_socket)
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 240, in __poll_socket
driver-parmesan-0_1  |     raise ConnectionException(f"Polling timed out")
driver-parmesan-0_1  | collabfuzz_generic_driver.connection.ConnectionException: Polling timed out
driver-symcc-0_1     |     self.__poll_socket(self._ctrl_socket)
driver-symcc-0_1     |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 240, in __poll_socket
driver-symcc-0_1     |     server_id = self._connection.push_test_case(seed_msg)
driver-symcc-0_1     |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 132, in push_test_case
driver-symcc-0_1     |     raise ConnectionException(f"Polling timed out")
driver-symcc-0_1     | collabfuzz_generic_driver.connection.ConnectionException: Polling timed out
driver-aflfast-0_1   |     raise ConnectionException(f"Polling timed out")
driver-aflfast-0_1   | collabfuzz_generic_driver.connection.ConnectionException: Polling timed out
driver-symcc-0_1     |     self.__poll_socket(self._report_socket)
driver-symcc-0_1     |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 240, in __poll_socket
driver-symcc-0_1     |     raise ConnectionException(f"Polling timed out")
driver-symcc-0_1     | collabfuzz_generic_driver.connection.ConnectionException: Polling timed out
driver-aflfast-0_1   | [2022-01-19 01:05:37,692 WARNING collabfuzz_generic_driver.connection receiver-thread] Polled socket for 0:00:10
driver-aflfast-0_1   | Exception in thread receiver-thread:
driver-aflfast-0_1   | Traceback (most recent call last):
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
driver-aflfast-0_1   |     self.run()

driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/threading.py", line 946, in run
driver-aflfast-0_1   |     self._target(*self._args, **self._kwargs)
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/receiver.py", line 126, in run
driver-aflfast-0_1   |     self._connection.report_ready()
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 178, in report_ready
driver-aflfast-0_1   |     self.__poll_socket(self._ctrl_socket)
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 240, in __poll_socket
driver-aflfast-0_1   |     raise ConnectionException(f"Polling timed out")
driver-aflfast-0_1   | collabfuzz_generic_driver.connection.ConnectionException: Polling timed out
driver-parmesan-0_1  | The watcher crashed, killing the remaining components
driver-parmesan-0_1  | [2022-01-19 01:05:37,834 INFO collabfuzz_generic_driver.watcher MainThread] Stopping watcher
driver-parmesan-0_1  | [2022-01-19 01:05:37,887 DEBUG collabfuzz_generic_driver.receiver MainThread] Waiting for polling to finish.
driver-afl-0_1       | [2022-01-19 01:05:38,167 WARNING collabfuzz_generic_driver.connection receiver-thread] Polled socket for 0:00:10
driver-afl-0_1       | Exception in thread receiver-thread:
driver-afl-0_1       | Traceback (most recent call last):
driver-afl-0_1       |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
driver-afl-0_1       |     self.run()
driver-afl-0_1       |   File "/usr/local/lib/python3.10/threading.py", line 946, in run
driver-afl-0_1       |     self._target(*self._args, **self._kwargs)
driver-afl-0_1       |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/receiver.py", line 126, in run
driver-afl-0_1       |     self._connection.report_ready()
driver-afl-0_1       |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 178, in report_ready
driver-afl-0_1       |     self.__poll_socket(self._ctrl_socket)
driver-afl-0_1       |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 240, in __poll_socket
driver-afl-0_1       |     raise ConnectionException(f"Polling timed out")
driver-afl-0_1       | collabfuzz_generic_driver.connection.ConnectionException: Polling timed out
driver-afl-0_1       | The receiver crashed, killing the remaining components
driver-afl-0_1       | [2022-01-19 01:05:38,168 INFO collabfuzz_generic_driver.watcher MainThread] Stopping watcher
driver-afl-0_1       | [2022-01-19 01:05:38,270 WARNING collabfuzz_generic_driver.connection push-thread] Polled socket for 0:00:10
driver-afl-0_1       | Exception in thread push-thread:
driver-afl-0_1       | Traceback (most recent call last):
driver-afl-0_1       |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
driver-afl-0_1       | [2022-01-19 01:05:38,270 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000010,src:000000,op:havoc,rep:64,+cov
driver-afl-0_1       |     self.run()
driver-afl-0_1       |   File "/usr/local/lib/python3.10/threading.py", line 946, in run
driver-afl-0_1       |     self._target(*self._args, **self._kwargs)

driver-aflfast-0_1   | [2022-01-19 01:29:31,335 WARNING collabfuzz_generic_driver.connection push-thread] Polled socket for 0:00:10
driver-aflfast-0_1   | Exception in thread push-thread:
driver-aflfast-0_1   | Traceback (most recent call last):
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
driver-aflfast-0_1   | [2022-01-19 01:29:31,335 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000007,src:000000,time:476,op:havoc,rep:8,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,335 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000008,src:000000,time:492,op:havoc,rep:16,+cov
driver-aflfast-0_1   |     self.run()
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/threading.py", line 946, in run
driver-aflfast-0_1   | [2022-01-19 01:29:31,336 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000009,src:000000,time:508,op:havoc,rep:16,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,336 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000010,src:000000,time:673,op:havoc,rep:8,+cov
driver-aflfast-0_1   |     self._target(*self._args, **self._kwargs)
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/watcher.py", line 194, in _push_thread_run
driver-aflfast-0_1   | [2022-01-19 01:29:31,336 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000011,src:000000,time:702,op:havoc,rep:8,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,336 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000012,src:000000,time:759,op:havoc,rep:16,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,336 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000013,src:000000,time:896,op:havoc,rep:2,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,336 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000014,src:000000,time:961,op:havoc,rep:4,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,336 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000015,src:000000,time:1048,op:havoc,rep:2,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,337 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000016,src:000000,time:1558,op:havoc,rep:8,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,337 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000017,src:000000,time:1606,op:havoc,rep:8,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,337 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000018,src:000000,time:2371,op:havoc,rep:8,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,337 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000019,src:000000,time:2610,op:havoc,rep:8,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,337 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000020,src:000000,time:3441,op:havoc,rep:2,+cov
driver-aflfast-0_1   |     self._process_test_case()
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/watcher.py", line 182, in _process_test_case
driver-aflfast-0_1   | [2022-01-19 01:29:31,337 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000021,src:000000,time:5983,op:havoc,rep:16,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,337 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000022,src:000000,time:6250,op:havoc,rep:16,+cov
driver-aflfast-0_1   | [2022-01-19 01:29:31,337 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000023,src:000000,time:7856,op:havoc,rep:16
driver-aflfast-0_1   |     server_id = self._connection.push_test_case(seed_msg)
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 132, in push_test_case
driver-aflfast-0_1   |     self.__poll_socket(self._report_socket)

driver-aflfast-0_1   |     server_id = self._connection.push_test_case(seed_msg)
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 132, in push_test_case
driver-aflfast-0_1   |     self.__poll_socket(self._report_socket)
driver-aflfast-0_1   |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 240, in __poll_socket
driver-aflfast-0_1   |     raise ConnectionException(f"Polling timed out")
driver-aflfast-0_1   | collabfuzz_generic_driver.connection.ConnectionException: Polling timed out
driver-afl-0_1       | [2022-01-19 01:29:31,376 WARNING collabfuzz_generic_driver.connection push-thread] Polled socket for 0:00:10
driver-afl-0_1       | Exception in thread push-thread:
driver-afl-0_1       | Traceback (most recent call last):
driver-afl-0_1       |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
driver-afl-0_1       | [2022-01-19 01:29:31,376 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000004,src:000000,op:int32,pos:0,val:be:+65535,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,376 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000005,src:000000,op:havoc,rep:32,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,376 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000006,src:000000,op:havoc,rep:64,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,377 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000007,src:000000,op:havoc,rep:16
driver-afl-0_1       | [2022-01-19 01:29:31,377 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000008,src:000000,op:havoc,rep:32,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,377 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000009,src:000000,op:havoc,rep:64,+cov
driver-afl-0_1       |     self.run()
driver-afl-0_1       | [2022-01-19 01:29:31,377 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000010,src:000000,op:havoc,rep:32,+cov
driver-afl-0_1       |   File "/usr/local/lib/python3.10/threading.py", line 946, in run
driver-afl-0_1       | [2022-01-19 01:29:31,377 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000011,src:000000,op:havoc,rep:4,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,377 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000012,src:000000,op:havoc,rep:4,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,377 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000013,src:000000,op:havoc,rep:64,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,378 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000014,src:000000,op:havoc,rep:64,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,378 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000015,src:000000,op:havoc,rep:8,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,378 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000016,src:000000,op:havoc,rep:128,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,378 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000017,src:000000,op:havoc,rep:4,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,378 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000018,src:000000,op:havoc,rep:32
driver-afl-0_1       | [2022-01-19 01:29:31,378 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000019,src:000000,op:havoc,rep:8,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,378 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000020,src:000000,op:havoc,rep:64,+cov
driver-afl-0_1       |     self._target(*self._args, **self._kwargs)
driver-afl-0_1       |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/watcher.py", line 194, in _push_thread_run
driver-afl-0_1       | [2022-01-19 01:29:31,378 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000021,src:000000,op:havoc,rep:32
driver-afl-0_1       | [2022-01-19 01:29:31,379 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000022,src:000000,op:havoc,rep:16,+cov
driver-afl-0_1       | [2022-01-19 01:29:31,379 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000023,src:000000,op:havoc,rep:64
driver-afl-0_1       | [2022-01-19 01:29:31,379 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000024,src:000000,op:havoc,rep:128

driver-aflfast-0_1  | [2022-01-19 02:20:34,707 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000012,src:000000,time:867,op:havoc,rep:16,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,707 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000013,src:000000,time:1274,op:havoc,rep:2,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,707 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000014,src:000000,time:1567,op:havoc,rep:4,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,707 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000015,src:000000,time:1721,op:havoc,rep:8,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,707 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000016,src:000000,time:1939,op:havoc,rep:4,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,707 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000017,src:000000,time:2270,op:havoc,rep:8,+cov
driver-aflfast-0_1  |     self.run()
driver-aflfast-0_1  | [2022-01-19 02:20:34,707 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000018,src:000000,time:2607,op:havoc,rep:8,+cov
driver-aflfast-0_1  |   File "/usr/local/lib/python3.10/threading.py", line 946, in run
driver-aflfast-0_1  | [2022-01-19 02:20:34,708 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000019,src:000000,time:2772,op:havoc,rep:16,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,708 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000020,src:000000,time:4398,op:havoc,rep:8,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,708 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000021,src:000000,time:4813,op:havoc,rep:8,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,708 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000022,src:000000,time:7555,op:havoc,rep:8
driver-aflfast-0_1  | [2022-01-19 02:20:34,708 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000023,src:000000,time:8079,op:havoc,rep:8,+cov
driver-aflfast-0_1  | [2022-01-19 02:20:34,708 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000024,src:000000,time:10419,op:havoc,rep:2,+cov
driver-aflfast-0_1  |     self._target(*self._args, **self._kwargs)
driver-aflfast-0_1  |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/watcher.py", line 194, in _push_thread_run
driver-aflfast-0_1  |     self._process_test_case()
driver-aflfast-0_1  |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/watcher.py", line 182, in _process_test_case
driver-aflfast-0_1  |     server_id = self._connection.push_test_case(seed_msg)
driver-aflfast-0_1  |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 132, in push_test_case
driver-aflfast-0_1  |     self.__poll_socket(self._report_socket)
driver-aflfast-0_1  |   File "/usr/local/lib/python3.10/site-packages/collabfuzz_generic_driver/connection.py", line 240, in __poll_socket
driver-aflfast-0_1  |     raise ConnectionException(f"Polling timed out")
driver-aflfast-0_1  | collabfuzz_generic_driver.connection.ConnectionException: Polling timed out
driver-aflfast-0_1  | [2022-01-19 02:20:34,748 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/aflfast-0/aflfast/queue/id:000025,src:000000,time:11072,op:havoc,rep:8,+cov
driver-afl-0_1      | [2022-01-19 02:20:34,751 WARNING collabfuzz_generic_driver.connection push-thread] Polled socket for 0:00:10
driver-afl-0_1      | Exception in thread push-thread:
driver-afl-0_1      | [2022-01-19 02:20:34,751 DEBUG collabfuzz_generic_driver.watcher Thread-1] Found new test case: /data/afl-0/afl/queue/id:000004,src:000000,op:int32,pos:0,val:be:+65535,+cov
driver-afl-0_1      | Traceback (most recent call last):
driver-afl-0_1      |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner



